replicaCount: 1

image:
  repository: yanisdjouima756/commande-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

containerPort: 8082

env:
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://discovery-service:8761/eureka"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-commande:5432/commandedb"
  - name: SPRING_DATASOURCE_DRIVER
    value: "org.postgresql.Driver"
  - name: SPRING_DATASOURCE_USERNAME
    value: "commande_user"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "commande_pass"
  - name: SPRING_JPA_PLATFORM
    value: "org.hibernate.dialect.PostgreSQLDialect"
