replicaCount: 1

image:
  repository: yanisdjouima756/paiement-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

containerPort: 8083

env:
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://discovery-service:8761/eureka"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-paiement:5432/paiementdb"
  - name: SPRING_DATASOURCE_DRIVER
    value: "org.postgresql.Driver"
  - name: SPRING_DATASOURCE_USERNAME
    value: "paiement_user"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "paiement_pass"
  - name: SPRING_JPA_PLATFORM
    value: "org.hibernate.dialect.PostgreSQLDialect"
