apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.password }}"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ .Values.username }}"
                - -d
                - "{{ .Values.database }}"
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "{{ .Values.username }}"
                - -d
                - "{{ .Values.database }}"
            initialDelaySeconds: 15
            periodSeconds: 10
